title: "OTEP一覧"
summary: "OpenTelemetry Enhancement Proposalの訳"
topics: ["OpenTelemetry", "otel"]
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - 0001-telemetry-without-manual-instrumentation
  - 0005-global-init
